### ISSUE TITLE
Change function signature from rest.API to rest.Send

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/rest#13]
#### Issue Summary

"API" reads to me like it's constructing an API structure based on some description (such as swagger or raml), and that method calls on that type would actually produce network requests. Based on the name "API", I wouldn't necessarily consider it to "do" anything, since it's not a verb

via @extemporalgenome

**Comment by adnrs96** [comment]
I will do this

**Comment by thinkingserious** [comment]
Thanks @adnrs96!

Please take a moment to sign our CLA so that we can merge your changes: https://github.com/sendgrid/rest/blob/master/CONTRIBUTING.md#cla

**Comment by adnrs96** [comment]
Would it be fine if i just email the agreement file with body of email saying I accept the terms as mentioned in the attachment. @thinkingserious 
This is mentioned in agreement.
Actually this is my first experience with agreement thing.

**Comment by thinkingserious** [comment]
Hello @adnrs96,

We need you to either 1) download, sign, scan and email it to us or 2) use a digital signing service like docusign.com or 3) use a PDF reader that allows you to digitally sign the document.

I hope that helps. Thanks!

**Comment by adnrs96** [comment]
@thinkingserious I have sent the email with doc signed to dx@sendgrid.com.

**Comment by EyesBear** [comment]
So was this issue never addressed? It looks like @thinkingserious had done it?

**Comment by thinkingserious** [comment]
Hi @PrincipalsOffice,

This will be solved with #19
