### ISSUE TITLE
Implementation of error Interface

### ISSUE THREAD

**Issue by iktakahiro** [sendgrid/rest#17]
A implementation of error Interface is helpful us. (https://blog.golang.org/error-handling-and-go)
## Suggestion

``` go
// RestError is a struct for an error handling.
type RestError struct {
    Response *Response
}

// Error is a implementation of error interface.
func (e *RestError) Error() string {
    return e.Response.Body
}
```
## How to Use

``` go
func doSomething() error {
    response, err := sendgrid.API(request)
    if err != nil {
        return err
    }
    if response.StatusCode != 201 {
        restErr := &rest.RestError{
            Response: response,
        }
    return restErr
    }
    return nil
}

///////

err := doSomething()
if restErr, ok := err.(*rest.RestError);ok {
    if restErr.Response.StatusCode == 400 {
            fmt.Println("Bad Request")
    } else if restErr.Reponse.StatusCode == 500 {
            fmt.Println("Internal Server Error")
    }
}
```

What do you think? If you also feel useful, I want to send PR.

Maybe RestError should be implement in sendgrid/sendgrid-go

**Comment by thinkingserious** [comment]
Hello @iktakahiro,

Great idea! I think it can be useful here and in the sendgrid-go library. 

Note that the dependency to this library from sendgrid-go is being removed, per this issue: https://github.com/sendgrid/sendgrid-go/issues/94

So this library will become stand alone and remain non-SendGrid specific.

With Best Regards,

Elmer
