### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/rest#21]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by DigitalDesignerOnline** [comment]
I can get this done right away. :)

**Comment by DigitalDesignerOnline** [comment]
can you direct me to the code of conduct page you want added as I am not seeing it within the root of the repo you noted.
