### ISSUE TITLE
Add megacheck to sendgrid/rest TravisCI checks

### ISSUE THREAD

**Issue by mbernier** [sendgrid/rest#57]
#### Issue Summary

Issue https://github.com/sendgrid/sendgrid-go/pull/215, came to be due to a code checking tool called [Megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) 

It would be awesome to have this running and breaking Travis builds if it finds something wrong with this library.

**Comment by mbernier** [comment]
I created a similar Issue in our 2 other Go repos:
- https://github.com/sendgrid/smtpapi-go/issues/50
- https://github.com/sendgrid/sendgrid-go/issues/227

**Comment by vaskoz** [comment]
I'll take this one.

**Comment by vaskoz** [comment]
Why use a single linter like **megacheck** when you can use all-of-them with [GoMetaLinter](https://github.com/alecthomas/gometalinter#supported-linters)?
