### ISSUE TITLE
Recent change to sendgrid/rest is breaking sendgrid/sendgrid-go

### ISSUE THREAD

**Issue by znas-io** [sendgrid/rest#67]
#### Issue Summary

Recent change to sendgrid/rest is breaking sendgrid/sendgrid-go. Ran
`go get github.com/sendgrid/sendgrid-go`

getting errors when building:
`../../vendor/github.com/sendgrid/sendgrid-go/sendgrid.go:49:2: not enough arguments to return`

`../../vendor/github.com/sendgrid/sendgrid-go/sendgrid.go:49:22: DefaultClient.API undefined (type *rest.Client has no field or method API)`

#### Steps to Reproduce

1. `go get github.com/sendgrid/sendgrid-go`
2. `go build`
3. errors

rest.Client.API function does not exist anymore and is still being used by sendgrid/sendgrid-go.

#### Technical details:

* package: github.com/sendgrid/sendgrid-go version: v3.4.1
* go version go1.9 darwin/amd64

**Comment by thinkingserious** [comment]
Thanks for reporting this @znas-io. The awesome @jerbob92 has fixed this with PR #68, which has already been merged.

My apologies for the breakage :(
