### ISSUE TITLE
BuildRequestObject should call AddQueryParameters

### ISSUE THREAD

**Issue by broady** [sendgrid/rest#7]
```
	// Add any query parameters to the URL.
	if len(request.QueryParams) != 0 {
		request.BaseURL = AddQueryParameters(request.BaseURL, request.QueryParams)
	}
```

This snippet should live inside `BuildRequestObject`

**Comment by akarki15** [comment]
i can give this a shot

**Comment by thinkingserious** [comment]
Awesome @akarki15!

For us to merge you pull request, we are going to need a signed CLA, could you please take care of that for us? https://github.com/sendgrid/rest/blob/master/CONTRIBUTING.md#cla

Thanks!
