### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/rest#79]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by Charliekenney23** [comment]
I'd like to take this.

**Comment by theag3nt** [comment]
I'd like to take this, as I did not see any open PRs for this since last year.

**Comment by childish-sambino** [comment]
Closing as we're moving to internal tooling for automated release notes.
