### ISSUE TITLE
[Feature Request] Can't pass context to requests

### ISSUE THREAD

**Issue by someone1** [sendgrid/rest#91]
#### Issue Summary

Currently, there is no way to pass the context along with any requests without manually building the request ourselves. It should be trivial to introduce a `SendWithContext` type function which is exactly like the original, but takes a `context.Context` as the first parameter and sets it on the built `http.Request`

Something like:

```go
func (c *Client) SendWithContext(ctx context.Context, request Request) (*Response, error) {
	req, err := BuildRequestObject(request)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)

	// Build the HTTP client and make the request.
	res, err := c.MakeRequest(req)
	if err != nil {
		return nil, err
	}

	// Build Response object.
	return rest.BuildResponse(res)
}
```

The alternative is to switch to the idiomatic http Request/Response types throughout but it looks like that issue/PR has been on hold for over a year? This seems like it'd be much faster to incorporate (no breaking changes introduced!)

**Comment by thinkingserious** [comment]
Great idea @someone1!

While we are hoping for the PR you mentioned to be merged soon, your solution seems like a great short term fix. I've added this to our backlog and also tagged it appropriately in case someone in the community would like to give a PR a shot which would increase the priority in our backlog.

Thank you!

With Best Regards,

Elmer

**Comment by sammy007** [comment]
So are we getting context in near future?

**Comment by thinkingserious** [comment]
Hello @sammy007,

I believe so. We are aiming for a consistent 2 week release cycle starting sometime this quarter. Since there is already a PR for this, I'm hopeful that means it will get released soon.

Please be sure to add your vote to this PR https://github.com/sendgrid/rest/pull/92, by adding a thumbs up, so that it gains priority in our backlog.

Thanks!

With best regards,

Elmer

**Comment by ConorNevin** [comment]
@thinkingserious Any idea on a timeframe for when the release cycle will start?
