### ISSUE TITLE
Document that a custom HTTP client should be used when deploying to AWS

### ISSUE THREAD

**Issue by bigokro** [sendgrid/rest#98]
https://github.com/sendgrid/rest/blob/5a76b291f6916f6a30a07b7060ae447480ec0e90/rest.go#L43

For reasons I still haven't figured out, the fact that the library uses http.DefaultClient for the client in calls to the API can result in the `Authorization: Bearer <API Key>` header being replaced by one determined by AWS. This doesn't happen all the time (in our case, it was always working in our dev server, but always failing on our prod server - maybe it's a race condition to set up the DefaultClient):

`Authorization:[AWS4-HMAC-SHA256 Credential=AKIATH.../us-east-1/es/aws4_request, SignedHeaders=accept;content-type;date;host;x-amz-date, Signature=368af...]`

I was able to fix the problem by replacing your library with a raw net/http request, and using a custom http.Client:

`client := &http.Client{Timeout: 3 * time.Second}`

This is now working in production.

**Comment by thinkingserious** [comment]
Hello @bigokrol,

Thank you for taking the time to report this issue. It looks like [AWS suggests that you supply a custom client](https://docs.aws.amazon.com/sdk-for-go/api/aws). Would it have been helpful if we documented this in the [TROUBLESHOOTING](https://github.com/sendgrid/rest/blob/master/TROUBLESHOOTING.md) section?

With best regards,

Elmer

**Comment by bigokro** [comment]
Perhaps... it's been a while, so I don't remember how I came to discover the problem and the (custom) solution. I don't remember finding the Troubleshooting section, so not sure if that would be the best place (but wouldn't hurt, of course). I think I never found how to define my own client. It seems like the biggest help would be to have defining your own client be part of the initial "getting started" documentation, along with a special note that you really should do this if you are calling from AWS (I imagine this would impact a lot of users, but I could be wrong).

All the best,
Tim

**Comment by thinkingserious** [comment]
Thats great feedback @bigokro! Thanks for taking the time to elaborate!

I agree that we should better surface the instructions on how to add a custom client with a special note that this is a strong suggestion for AWS users. I will rename and tag this issue accordingly.

**Comment by childish-sambino** [comment]
I think it's better just to not use the default client in this lib. The line should be changed to just use a new client:
```
 var DefaultClient = &Client{HTTPClient: &http.Client{}}
```

**Comment by mateorider** [comment]
I'd be happy to pick this up (first issue). Should I just update the docs or should I update the actual var as suggested above?

**Comment by childish-sambino** [comment]
@mateorider I think just updating the var is fine. It's all yours!
