### ISSUE TITLE
Version tags with vMajor.Minor.Patch (with v prefix)

### ISSUE THREAD

**Issue by ebati** [sendgrid/rest#99]
### Issue Summary

You do not use go modules but tagging release with vX.X.X would help to discover versions much easier for module users. As [go modules](https://github.com/golang/go/wiki/Modules#modules) seek for vX.X.X format.

**Comment by childish-sambino** [comment]
Ah, TIL. I'll look at fixing this.

**Comment by childish-sambino** [comment]
Fixed.
